#!/usr/bin/env bash
# HandBrake Cutter

set -e
USAGE='usage: [OUTDIR=output_directory] hbc FILENAME START-TIME STOP-TIME'

show_help() {
   echo "$USAGE" >&2
}

# Convert format time (HH:MM:SS) to seconds
time2seconds() {
    echo "$1" | awk -F: '{
        if (NF > 3) {
            print "Invalid time format." > "/dev/stderr" 
            exit 1
        }
        base = 60
        res = 0
        for (i = 1; i <= NF; i++) { 
            res = res * base + $i 
        }
        print res
    }'
}

[ $# -ne 3 ] && {
    show_help
    exit 1
}

eval OUTDIR="${OUTDIR:-~/.hbc}"
mkdir -p "$OUTDIR"
FILENAME=$(echo ${1// /_})
START_TIME=$(time2seconds $2)
STOP_TIME=$(time2seconds $3)
echo "Output directory is $OUTPUT_DIR."
which HandBrakeCLI &> /dev/null || {
    echo 'HandBrakeCLI command is not found. Please install it to PATH.' >&2
    exit 1
}
HandBrakeCLI -i "$1" -o "$OUTDIR/$(basename $FILENAME)" \
    --start-at duration:$START_TIME \
    --stop-at duration:$(echo "$STOP_TIME - $START_TIME" | bc)
